
slam_toolbox:
  ros__parameters:

    # Use Gazebo clock
    use_sim_time: true

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Frames / topics
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: localization   # later you can switch to localization / mapping
  

    # Timing & TF
    transform_publish_period: 0.02   # s, publishes map->odom
    map_update_interval: 2.0         # s
    minimum_time_interval: 0.0
    transform_timeout: 0.2
    tf_buffer_duration: 10.0

    # Map properties
    resolution: 0.05                 # m/cell
    max_laser_range: 8.0             # matches your lidar range
    min_laser_range: 0.15  
    # Internal buffers
    stack_size_to_use: 40000000
    scan_buffer_size: 50
    scan_buffer_maximum_scan_distance: 10.0
    throttle_scans: 1   

    # Scan matching & loop closure (reasonable defaults)
    use_scan_matching: true
    use_scan_barycenter: false
    minimum_travel_distance: 0.10
    minimum_travel_heading: 0.17
    loop_search_maximum_distance: 04.0
    do_loop_closing: true
    enable_interactive_mode: true
    do_relocalization: true
    loop_search_radius: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_maximum_variance_fine: 0.5
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 3.0

    correlation_search_space_dimension: 0.5         # [m]
    correlation_search_space_resolution: 0.01       # [m]
    correlation_search_space_smear_deviation: 0.1

    loop_search_space_dimension: 8.0                # [m]
    loop_search_space_resolution: 0.05              # [m]
    loop_search_space_smear_deviation: 0.03

    distance_variance_penalty: 0.5
    angle_variance_penalty: 0.5

    fine_search_angle_offset: 0.00349     # ~0.2 deg
    coarse_search_angle_offset: 0.9       # [rad]
    coarse_angle_resolution: 0.0349       # ~2 deg
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true